name: Release

on: 
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build release and report to SonarQube Cloud
        run: mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.organization=sonar-auth-oidc -Dsonar.projectKey=sonar-auth-oidc_sonar-auth-oidc -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release with plugin jar
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/*.jar"
          artifactContentType: application/jar
          token: ${{ secrets.GITHUB_TOKEN }}
